// ヒヤリハット登録用カテゴリー
export const CATEGORY_ALL = '全てのカテゴリー';
export const CATEGORY_EQUIPMENT = '設備';
export const CATEGORY_ENVIRONMENTAL = '環境';
export const CATEGORY_WORK = '作業';
export const CATEGORY_HUMAN = '人為';
export const CATEGORY_SAFETY_ACCIDENT = '安全事故';
export const CATEGORY_EQUIPMENT_FAILURE = '設備故障';
export const CATEGORY_PROCESS_DEVIATION = '工程異常';
export const CATEGORY_QUALITY_ISSUE = '品質問題';
export const CATEGORY_HUMAN_ERROR = 'ヒューマンエラー';
export const CATEGORY_COMMUNICATION = 'コミュニケーション';
export const CATEGORY_MAINTENANCE = 'メンテナンス';
export const CATEGORY_OTHERS = 'その他';

export const HIYARI_HAT_CATEGORY_VALUES = [
  CATEGORY_EQUIPMENT,
  CATEGORY_ENVIRONMENTAL,
  CATEGORY_WORK,
  CATEGORY_HUMAN,
  CATEGORY_SAFETY_ACCIDENT,
  CATEGORY_EQUIPMENT_FAILURE,
  CATEGORY_PROCESS_DEVIATION,
  CATEGORY_QUALITY_ISSUE,
  CATEGORY_HUMAN_ERROR,
  CATEGORY_COMMUNICATION,
  CATEGORY_MAINTENANCE,
  CATEGORY_OTHERS,
] as const;

export const HIYARI_HAT_CATEGORY_OPTIONS = [
  { value: CATEGORY_EQUIPMENT, label: CATEGORY_EQUIPMENT },
  { value: CATEGORY_ENVIRONMENTAL, label: CATEGORY_ENVIRONMENTAL },
  { value: CATEGORY_WORK, label: CATEGORY_WORK },
  { value: CATEGORY_HUMAN, label: CATEGORY_HUMAN },
  { value: CATEGORY_SAFETY_ACCIDENT, label: CATEGORY_SAFETY_ACCIDENT },
  { value: CATEGORY_EQUIPMENT_FAILURE, label: CATEGORY_EQUIPMENT_FAILURE },
  { value: CATEGORY_PROCESS_DEVIATION, label: CATEGORY_PROCESS_DEVIATION },
  { value: CATEGORY_QUALITY_ISSUE, label: CATEGORY_QUALITY_ISSUE },
  { value: CATEGORY_HUMAN_ERROR, label: CATEGORY_HUMAN_ERROR },
  { value: CATEGORY_COMMUNICATION, label: CATEGORY_COMMUNICATION },
  { value: CATEGORY_MAINTENANCE, label: CATEGORY_MAINTENANCE },
  { value: CATEGORY_OTHERS, label: CATEGORY_OTHERS },
] as const;
