// 大カテゴリー
export const CATEGORY_ALL = '全てのカテゴリー';
export const CATEGORY_HR = '人事';
export const CATEGORY_GENERAL = '総務・庶務';
export const CATEGORY_LEGAL = '法務・コンプライアンス';
export const CATEGORY_AUDIT = '監査';
export const CATEGORY_FINANCE = '経理・財務';
export const CATEGORY_PR = '広報';
export const CATEGORY_PROCUREMENT = '調達';
export const CATEGORY_EDUCATION = '教育';
export const CATEGORY_IT = 'ITシステム';
export const CATEGORY_WELFARE = '福利厚生';
export const CATEGORY_PRODUCTION = '生産';
export const CATEGORY_QUALITY = '品質管理';
export const CATEGORY_OTHER = 'その他';

// サブカテゴリー
export const SUB_CATEGORY_ALL = '全てのサブカテゴリー';
// 人事
export const SUB_CATEGORY_ATTENDANCE = '勤怠';
export const SUB_CATEGORY_TRANSFER = '異動関連';
export const SUB_CATEGORY_RECRUITMENT = '採用関連';
export const SUB_CATEGORY_ONBOARDING = '入社手続き';
export const SUB_CATEGORY_WORK_RULES = '就業規則';
export const SUB_CATEGORY_EVALUATION = '評価';
export const SUB_CATEGORY_RETIREMENT = '離職手続き';

// 総務・庶務
export const SUB_CATEGORY_FACILITIES = '社内設備';
export const SUB_CATEGORY_SUPPLIES = '備品管理';
export const SUB_CATEGORY_MAIL = '郵便';
export const SUB_CATEGORY_HEALTH = '健康管理';
export const SUB_CATEGORY_EVENTS = '社内イベント';

// 法務・コンプライアンス
export const SUB_CATEGORY_INTERNAL_RULES = '社内規則';
export const SUB_CATEGORY_CONTRACT = '契約支援';
export const SUB_CATEGORY_IP = '知的財産権';
export const SUB_CATEGORY_LEGAL_PROCEDURE = '法的手続き';
export const SUB_CATEGORY_EXPORT_CONTROL = '輸出管理';

// 監査
export const SUB_CATEGORY_INTERNAL_AUDIT = '内部監査';
export const SUB_CATEGORY_EXTERNAL_AUDIT = '外部監査';

// 経理・財務
export const SUB_CATEGORY_EXPENSE = '経費精算';
export const SUB_CATEGORY_SETTLEMENT = '決算';
export const SUB_CATEGORY_TAX = '税務対応';
export const SUB_CATEGORY_COST = '原価管理';

// 広報
export const SUB_CATEGORY_AD = '広告・宣伝';
export const SUB_CATEGORY_INTERNAL_PR = '社内広報';
export const SUB_CATEGORY_SUSTAINABILITY = 'サステナビリティ';
export const SUB_CATEGORY_BRAND = 'ブランドマネジメント';

// 調達
export const SUB_CATEGORY_PURCHASE = '購入手続き';
export const SUB_CATEGORY_PROCUREMENT_RULES = '調達規則';
export const SUB_CATEGORY_SUPPLIER = 'サプライヤー関連';

// 教育
export const SUB_CATEGORY_YOUTH_EDU = '若年層教育';
export const SUB_CATEGORY_TRAINING = '社内研修・eラーニング';
export const SUB_CATEGORY_CERTIFICATION_SUPPORT = '資格取得支援';

// ITシステム
export const SUB_CATEGORY_ACCOUNT = 'アカウント・パスワード';
export const SUB_CATEGORY_INTERNAL_SYSTEM = '社内システム';

// 福利厚生
export const SUB_CATEGORY_INSURANCE = '保険';
export const SUB_CATEGORY_HOUSING = '住宅';
export const SUB_CATEGORY_CLUB = 'クラブ活動';
export const SUB_CATEGORY_RECREATION = 'レクリエーション';

// 生産
export const SUB_CATEGORY_PRODUCT_PLANNING = '製品企画';
export const SUB_CATEGORY_PRODUCT_DESIGN = '製品設計';
export const SUB_CATEGORY_PRODUCTION_CONTROL = '生産管理';

// 品質管理
export const SUB_CATEGORY_QUALITY_INSPECTION = '品質検査';
export const SUB_CATEGORY_DEFECT = '不具合管理';
export const SUB_CATEGORY_CERTIFICATION = '認証';

// その他
export const SUB_CATEGORY_OTHER_CORPORATE = 'その他（コーポレート）';
export const SUB_CATEGORY_OTHER_MANUFACTURING = 'その他（製造業）';

// カテゴリー配列
export const CATEGORY_VALUES = [
  CATEGORY_HR,
  CATEGORY_GENERAL,
  CATEGORY_LEGAL,
  CATEGORY_AUDIT,
  CATEGORY_FINANCE,
  CATEGORY_PR,
  CATEGORY_PROCUREMENT,
  CATEGORY_EDUCATION,
  CATEGORY_IT,
  CATEGORY_WELFARE,
  CATEGORY_PRODUCTION,
  CATEGORY_QUALITY,
  CATEGORY_OTHER,
] as const;

// サブカテゴリー配列（大カテゴリごと）
export const SUB_CATEGORY_VALUES_HR = [
  SUB_CATEGORY_ATTENDANCE,
  SUB_CATEGORY_TRANSFER,
  SUB_CATEGORY_RECRUITMENT,
  SUB_CATEGORY_ONBOARDING,
  SUB_CATEGORY_WORK_RULES,
  SUB_CATEGORY_EVALUATION,
  SUB_CATEGORY_RETIREMENT,
] as const;

export const SUB_CATEGORY_VALUES_GENERAL = [
  SUB_CATEGORY_FACILITIES,
  SUB_CATEGORY_SUPPLIES,
  SUB_CATEGORY_MAIL,
  SUB_CATEGORY_HEALTH,
  SUB_CATEGORY_EVENTS,
] as const;

export const SUB_CATEGORY_VALUES_LEGAL = [
  SUB_CATEGORY_INTERNAL_RULES,
  SUB_CATEGORY_CONTRACT,
  SUB_CATEGORY_IP,
  SUB_CATEGORY_LEGAL_PROCEDURE,
  SUB_CATEGORY_EXPORT_CONTROL,
] as const;

export const SUB_CATEGORY_VALUES_AUDIT = [
  SUB_CATEGORY_INTERNAL_AUDIT,
  SUB_CATEGORY_EXTERNAL_AUDIT,
] as const;

export const SUB_CATEGORY_VALUES_FINANCE = [
  SUB_CATEGORY_EXPENSE,
  SUB_CATEGORY_SETTLEMENT,
  SUB_CATEGORY_TAX,
  SUB_CATEGORY_COST,
] as const;

export const SUB_CATEGORY_VALUES_PR = [
  SUB_CATEGORY_AD,
  SUB_CATEGORY_INTERNAL_PR,
  SUB_CATEGORY_SUSTAINABILITY,
  SUB_CATEGORY_BRAND,
] as const;

export const SUB_CATEGORY_VALUES_PROCUREMENT = [
  SUB_CATEGORY_PURCHASE,
  SUB_CATEGORY_PROCUREMENT_RULES,
  SUB_CATEGORY_SUPPLIER,
] as const;

export const SUB_CATEGORY_VALUES_EDUCATION = [
  SUB_CATEGORY_YOUTH_EDU,
  SUB_CATEGORY_TRAINING,
  SUB_CATEGORY_CERTIFICATION_SUPPORT,
] as const;

export const SUB_CATEGORY_VALUES_IT = [SUB_CATEGORY_ACCOUNT, SUB_CATEGORY_INTERNAL_SYSTEM] as const;

export const SUB_CATEGORY_VALUES_WELFARE = [
  SUB_CATEGORY_INSURANCE,
  SUB_CATEGORY_HOUSING,
  SUB_CATEGORY_CLUB,
  SUB_CATEGORY_RECREATION,
] as const;

export const SUB_CATEGORY_VALUES_PRODUCTION = [
  SUB_CATEGORY_PRODUCT_PLANNING,
  SUB_CATEGORY_PRODUCT_DESIGN,
  SUB_CATEGORY_PRODUCTION_CONTROL,
] as const;

export const SUB_CATEGORY_VALUES_QUALITY = [
  SUB_CATEGORY_QUALITY_INSPECTION,
  SUB_CATEGORY_DEFECT,
  SUB_CATEGORY_CERTIFICATION,
] as const;

export const SUB_CATEGORY_VALUES_OTHER = [
  SUB_CATEGORY_OTHER_CORPORATE,
  SUB_CATEGORY_OTHER_MANUFACTURING,
] as const;

export const SUB_CATEGORY_MAP = {
  [CATEGORY_HR]: SUB_CATEGORY_VALUES_HR,
  [CATEGORY_GENERAL]: SUB_CATEGORY_VALUES_GENERAL,
  [CATEGORY_LEGAL]: SUB_CATEGORY_VALUES_LEGAL,
  [CATEGORY_AUDIT]: SUB_CATEGORY_VALUES_AUDIT,
  [CATEGORY_FINANCE]: SUB_CATEGORY_VALUES_FINANCE,
  [CATEGORY_PR]: SUB_CATEGORY_VALUES_PR,
  [CATEGORY_PROCUREMENT]: SUB_CATEGORY_VALUES_PROCUREMENT,
  [CATEGORY_EDUCATION]: SUB_CATEGORY_VALUES_EDUCATION,
  [CATEGORY_IT]: SUB_CATEGORY_VALUES_IT,
  [CATEGORY_WELFARE]: SUB_CATEGORY_VALUES_WELFARE,
  [CATEGORY_PRODUCTION]: SUB_CATEGORY_VALUES_PRODUCTION,
  [CATEGORY_QUALITY]: SUB_CATEGORY_VALUES_QUALITY,
  [CATEGORY_OTHER]: SUB_CATEGORY_VALUES_OTHER,
} as const;
