export const ALLOW_CONTAINER_NAMES = [
  process.env.NEXT_PUBLIC_STANDARD_STORAGE_CONTAINER_NAME,
  process.env.FILE_PREVIEW_CONTAINER_NAME,
  process.env.NEXT_PUBLIC_STANDARD_PREVIEW_STORAGE_CONTAINER_NAME,
];
