{
  "MODEL_IDENTIFIER": "genashi-trial",
  "LOAD_BALANCER_ENDPOINT": "${loadbalancer_url}",
  "AZURE_OPENAI_VERSION": "2025-04-01-preview",
  "TEMPERATURE": "0",
  "AZURE_AISEARCH_ENDPOINT": "TEST",
  "AZURE_AISEARCH_INDEX_NAME": "TEST",
  "AZURE_OPENAI_EMBEDDING_ENDPOINT": "https://app-load-balancer-genashi-trial-${environment_prefix}-01-bwd7hsf0c6bmfte6.japanwest-01.azurewebsites.net/",
  "AZURE_OPENAI_EMBEDDING_API_VERSION": "2025-04-01-preview",
  "AZURE_OPENAI_EMBEDDING_MODEL": "dummy",
  "AZURE_STORAGE_ACCOUNT_NAME": "stgenashitrial${environment_prefix}",
  "AZURE_STORAGE_TEMP_FILE_CONTAINER_NAME": "genashi-trial-05",
  "AZURE_COSMOSDB_URI": "https://cosno-genashi-trial-${environment_prefix}.documents.azure.com:443/",
  "AZURE_COSMOSDB_DATABASE_NAME": "cosmos-genashi-trial-01",
  "AZURE_COSMOSDB_DICTIONARY_CONTAINER_NAME": "dictionary",
  "AZURE_OPEN_AI_IMAGE_ENDPOINT": "https://oai-name-004.openai.azure.com/",
  "AZURE_OPENAI_IMAGE_VERSION": "2025-04-01-preview",
  "AZURE_STORAGE_CONTAINER_NAME": "st-image-container-name",
  "BING_SEARCH_API_KEY": "TEST",
  "BING_SEARCH_ENDPOINT": "TEST",
  "BUILD_FLAGS": "UseExpressBuild",
  "ENABLE_ORYX_BUILD": "true",
  "FUNCTIONS_EXTENSION_VERSION": "~4",
  "FUNCTIONS_WORKER_RUNTIME": "python",
  "SCM_DO_BUILD_DURING_DEPLOYMENT": "1",
  "WEBSITE_RUN_FROM_PACKAGE": "1",
  "XDG_CACHE_HOME": "/tmp/.cache"
}
