{
  "ALLOWED_GROUPS": "${security_group_object_id}",
  "ApplicationInsightsAgent_EXTENSION_VERSION": "~3",

  "AZURE_COSMOSDB_ADVICE_CONSULTING_CONTAINER_NAME": "advice-consulting",
  "AZURE_COSMOSDB_ADVICE_REACT_CONTAINER_NAME": "advice-react",
  "AZURE_COSMOSDB_AGENT_MESSAGE_CONTAINER_NAME": "message-agent",
  "AZURE_COSMOSDB_AGENT_THREAD_CONTAINER_NAME": "thread-agent",
  "AZURE_COSMOSDB_BAN_WORD_CONTAINER_NAME": "ban-word",
  "AZURE_COSMOSDB_BRAINSTORMING_CONTAINER_NAME": "brainstorming",
  "AZURE_COSMOSDB_BUSINESS_PLAN_CONTAINER_NAME": "business-plan",
  "AZURE_COSMOSDB_CODE_EXPLANATION_CONTAINER_NAME": "code-explanation",
  "AZURE_COSMOSDB_COMPANY_ANALYSIS_CONTAINER_NAME": "company-analysis",
  "AZURE_COSMOSDB_CORPORATE_SURVEY_CONTAINER_NAME": "corporate-survey",
  "AZURE_COSMOSDB_CREATE_DESIGN_DOCUMENT_CONTAINER_NAME": "create-design-document",
  "AZURE_COSMOSDB_CREATE_IDEA_CONTAINER_NAME": "create-idea",
  "AZURE_COSMOSDB_CREATE_MINUTES_CONTAINER_NAME": "create-minutes",
  "AZURE_COSMOSDB_CREATE_NEW_MAIL_CONTAINER_NAME": "create-mail",
  "AZURE_COSMOSDB_CREATE_TECHNOLOGY_PROPOSAL_CONTAINER_NAME": "create-technology-proposal",
  "AZURE_COSMOSDB_CRISIS_MANAGEMENT_SCENARIOS_CONTAINER_NAME": "crisis-management-scenarios",
  "AZURE_COSMOSDB_DATABASE_NAME": "cosmos-genashi-trial-01",
  "AZURE_COSMOSDB_DATABASE_NAME_02": "cosmos-genashi-trial-02",
  "AZURE_COSMOSDB_DATABASE_NAME_03": "cosmos-genashi-trial-03",
  "AZURE_COSMOSDB_DATABASE_NAME_04": "cosmos-genashi-trial-04",
  "AZURE_COSMOSDB_DEEP_MESSAGE_CONTAINER_NAME": "message",
  "AZURE_COSMOSDB_DEEP_THREAD_CONTAINER_NAME": "thread",
  "AZURE_COSMOSDB_DEFECT_ANALYSIS_REPORT_CONTAINER_NAME": "defect-analysis-report",
  "AZURE_COSMOSDB_DESIGN_DOCUMENT_REVIEW_CONTAINER_NAME": "design-document-review",
  "AZURE_COSMOSDB_DESIGN_DOCUMENT_REVIEW_NAME": "design-document-review",
  "AZURE_COSMOSDB_DICTIONARY_CONTAINER_NAME": "dictionary",
  "AZURE_COSMOSDB_ERROR_ANALYSIS_CONTAINER_NAME": "error-analysis",
  "AZURE_COSMOSDB_FLOW_DESIGNER_CONTAINER_NAME": "flow-designer",
  "AZURE_COSMOSDB_HIYARI_HAT_REGISTER_CONTAINER_NAME": "hiyari-hat",
  "AZURE_COSMOSDB_HIYARI_HAT_SEARCH_CONTAINER_NAME": "hiyari-hat-search",
  "AZURE_COSMOSDB_IMAGE_GENERATION_CONTAINER_NAME": "image-generation",
  "AZURE_COSMOSDB_INCIDENT_REPORT_CONTAINER_NAME": "incident-report",
  "AZURE_COSMOSDB_JUDGE_IDEA_CONTAINER_NAME": "judge-idea",
  "AZURE_COSMOSDB_KEY_POINT_EXTRACTION_CONTAINER_NAME": "key-point-extraction",
  "AZURE_COSMOSDB_MARKET_RESEARCH_CONTAINER_NAME": "market-research",
  "AZURE_COSMOSDB_MARKETING_STRATEGY_CONTAINER_NAME": "marketing-strategy",
  "AZURE_COSMOSDB_MESSAGE_CONTAINER_NAME": "message",
  "AZURE_COSMOSDB_MODIFY_SUPPOSED_QUESTION_CONTAINER_NAME": "supposed-question",
  "AZURE_COSMOSDB_NEEDS_SURVEY_CONTAINER_NAME": "needs-survey",
  "AZURE_COSMOSDB_NEW_PRODUCT_PROPOSAL_CONTAINER_NAME": "new-product-proposal",
  "AZURE_COSMOSDB_PRODUCT_AARRR_CONTAINER_NAM": "product-expansion-aarrr",
  "AZURE_COSMOSDB_PRODUCT_AARRR_CONTAINER_NAME": "product-expansion-aarrr",
  "AZURE_COSMOSDB_PRODUCT_CATCHPHRASE_CONTAINER_NAME": "product-catchphrase",
  "AZURE_COSMOSDB_PRODUCT_PROMOTION_STRATEGY_CONTAINER_NAME": "product-promotion-strategy",
  "AZURE_COSMOSDB_PRODUCT_SERVICE_BENEFIT_IDEA_CONTAINER_NAME": "product-service-benefit-idea",
  "AZURE_COSMOSDB_PRODUCTION_TECH_LIST_CONTAINER_NAME": "production-tech-list",
  "AZURE_COSMOSDB_PROMPT_CONTAINER_NAME": "create-prompt",
  "AZURE_COSMOSDB_QA_CONTAINER_NAME": "past-qa",
  "AZURE_COSMOSDB_QUALITY_REPORT_CONTAINER_NAME": "quality-report",
  "AZURE_COSMOSDB_QUALITY_STANDARD_DOCUMENT_CONTAINER_NAME": "quality-standard-document",
  "AZURE_COSMOSDB_RAG_MESSAGE_CONTAINER_NAME": "message-rag",
  "AZURE_COSMOSDB_RAG_THREAD_CONTAINER_NAME": "thread-rag",
  "AZURE_COSMOSDB_RESEARCH_REPORT_CONTAINER_NAME": "research-report",
  "AZURE_COSMOSDB_RISK_ASSESSMENT_CONTAINER_NAME": "risk-assessment",
  "AZURE_COSMOSDB_SALES_FORECAST_CONTAINER_NAME": "sales-forecast",
  "AZURE_COSMOSDB_SCHEDULE_CONTAINER_NAME": "schedule",
  "AZURE_COSMOSDB_SUMMARY_CONTAINER_NAME": "summary",
  "AZURE_COSMOSDB_TALK_SCRIPT_CONTAINER_NAME": "talk-script",
  "AZURE_COSMOSDB_TASK_BREAKDOWN_CONTAINER_NAME": "task-breakdown",
  "AZURE_COSMOSDB_TECHASSESS_CONTAINER_NAME": "tech-assess",
  "AZURE_COSMOSDB_TECHNOLOGY_TRAINING_CONTAINER_NAME": "technology-training",
  "AZURE_COSMOSDB_TEMPLATE_CONTAINER_NAME": "template",
  "AZURE_COSMOSDB_TEXT_CHECK_CONTAINER_NAME": "text-check",
  "AZURE_COSMOSDB_TEXT_CORRECTION_CONTAINER_NAME": "text-correction",
  "AZURE_COSMOSDB_THREAD_CONTAINER_NAME": "thread",
  "AZURE_COSMOSDB_TRANSCRIPTION_HANDWRITTEN_CONTAINER_NAME": "transcription-handwritten",
  "AZURE_COSMOSDB_TRANSLATE_CONTAINER_NAME": "translation",
  "AZURE_COSMOSDB_TROUBLE_SHOOTING_GUIDE_CONTAINER_NAME": "trouble-shooting-guide",
  "AZURE_COSMOSDB_URI": "https://cosno-genashi-trial-${environment_prefix}.documents.azure.com:443/",
  "AZURE_COSMOSDB_USE_CASE_CONTAINER_NAME": "use-case-search",
  "AZURE_COSMOSDB_VOICE_MESSAGE_CONTAINER_NAME": "test",
  "AZURE_COSMOSDB_VOICE_THREAD_CONTAINER_NAME": "test",
  "AZURE_COSMOSDB_WALL_HITTING_CONTAINER_NAME": "wall-hitting",

  "NEXT_PUBLIC_DISABLED_ROUTE_PREFIXES": "image-generation,create-manual",
  "NEXT_PUBLIC_STANDARD_PREVIEW_STORAGE_CONTAINER_NAME": "genashi-trial-06",
  "NEXT_PUBLIC_STANDARD_STORAGE_CONTAINER_NAME": "genashi-trial-06",

  "ORCHESTRATOR_AGENT_API_CREDENTIAL":"@Microsoft.KeyVault(VaultName=kv-genashi-trial-${environment_prefix};SecretName=ORCHESTRATOR-AGENT-API-CREDENTIAL)",
  "ORCHESTRATOR_AGENT_API_ENDPOINT": "https://func-genashi-trial-${environment_prefix}-10-agent-rag.azurewebsites.net/api",
  "ORCHESTRATOR_API_URL":"@Microsoft.KeyVault(VaultName=kv-genashi-trial-${environment_prefix};SecretName=ORCHESTRATOR-API-URL)",
  "ORCHESTRATOR_DOCUMENT_API_CREDENTIAL":"@Microsoft.KeyVault(VaultName=kv-genashi-trial-${environment_prefix};SecretName=ORCHESTRATOR-DOCUMENT-API-CREDENTIAL)",
  "ORCHESTRATOR_DOCUMENT_API_ENDPOINT": "https://func-genashi-trial-${environment_prefix}-03-text-register.azurewebsites.net/api/",
  "ORCHESTRATOR_FILE_API_CREDENTIAL":"@Microsoft.KeyVault(VaultName=kv-genashi-trial-${environment_prefix};SecretName=ORCHESTRATOR-FILE-API-CREDENTIAL)",
  "ORCHESTRATOR_FILE_API_ENDPOINT": "https://func-genashi-trial-${environment_prefix}-01-chat.azurewebsites.net/api/",
  "ORCHESTRATOR_IT_API_CREDENTIAL":"@Microsoft.KeyVault(VaultName=kv-genashi-trial-${environment_prefix};SecretName=ORCHESTRATOR-MFG-API-CREDENTIAL)",
  "ORCHESTRATOR_IT_API_ENDPOINT": "https://func-genashi-trial-${environment_prefix}-09-mfg.azurewebsites.net/api",
  "ORCHESTRATOR_MANUAL_API_CREDENTIAL":"dummy",
  "ORCHESTRATOR_MANUAL_API_ENDPOINT": "dummy",
  "ORCHESTRATOR_MFG_API_CREDENTIAL":"@Microsoft.KeyVault(VaultName=kv-genashi-trial-${environment_prefix};SecretName=ORCHESTRATOR-MFG-API-CREDENTIAL)",
  "ORCHESTRATOR_MFG_API_ENDPOINT": "https://func-genashi-trial-${environment_prefix}-09-mfg.azurewebsites.net/api",
  "ORCHESTRATOR_PII_API_URL":"@Microsoft.KeyVault(VaultName=kv-genashi-trial-${environment_prefix};SecretName=ORCHESTRATOR-PII-API-URL)",
  "ORCHESTRATOR_RAG_API_URL":"@Microsoft.KeyVault(VaultName=kv-genashi-trial-${environment_prefix};SecretName=ORCHESTRATOR-RAG-API-URL)",
  "ORCHESTRATOR_STANDARD_API_CREDENTIAL":"@Microsoft.KeyVault(VaultName=kv-genashi-trial-${environment_prefix};SecretName=ORCHESTRATOR-STANDARD-API-CREDENTIAL)",
  "ORCHESTRATOR_STANDARD_API_ENDPOINT": "https://func-genashi-trial-${environment_prefix}-11-agent-document.azurewebsites.net/api/",
  "ORCHESTRATOR_USE_CASE_API_CREDENTIAL":"@Microsoft.KeyVault(VaultName=kv-genashi-trial-${environment_prefix};SecretName=ORCHESTRATOR-USE-CASE-API-CREDENTIAL)",
  "ORCHESTRATOR_USE_CASE_API_ENDPOINT": "https://func-genashi-trial-${environment_prefix}-05-prompt.azurewebsites.net/api",

  "SCM_DO_BUILD_DURING_DEPLOYMENT": "true",
  "WEBSITE_AUTH_AAD_ALLOWED_TENANTS": "${tenant_id}",
  "WEBSITE_CONTENTOVERVNET": "1",
  "WEBSITE_HTTPLOGGING_RETENTION_DAYS": "3",
  "XDT_MicrosoftApplicationInsights_Mode": "default",

  "NEXT_PUBLIC_AOAI_ENDPOINT": "dummy",
  "NEXT_PUBLIC_AOAI_MODEL_NAME": "dummy"
}
