// カテゴリー
export const CATEGORY_ALL = '全てのカテゴリー';
export const CATEGORY_CONFIDENTIAL = '機密情報と社外秘';
export const CATEGORY_PERSONAL_INFORMATION = '個人情報';
export const CATEGORY_DISCRIMINATION = '差別的・不適切な表現';
export const CATEGORY_VIOLATION_OF_TERMS = '社内規定違反';
export const CATEGORY_COPYRIGHT = '著作権・商標侵害';
export const CATEGORY_VIOLENCE = '暴力的・攻撃的な表現';
export const CATEGORY_CHEATING = '不正行為関連';
export const CATEGORY_ETHICS = '倫理に反する表現';
export const CATEGORY_SPAM = 'スパム・迷惑行為関連';
export const CATEGORY_MISUSE = '業界用語の誤用';

export const CATEGORY_VALUES = [
  CATEGORY_CONFIDENTIAL,
  CATEGORY_PERSONAL_INFORMATION,
  CATEGORY_DISCRIMINATION,
  CATEGORY_VIOLATION_OF_TERMS,
  CATEGORY_COPYRIGHT,
  CATEGORY_VIOLENCE,
  CATEGORY_CHEATING,
  CATEGORY_ETHICS,
  CATEGORY_SPAM,
  CATEGORY_MISUSE,
] as const;

export const CATEGORY_OPTIONS = [
  { value: CATEGORY_CONFIDENTIAL, label: CATEGORY_CONFIDENTIAL },
  { value: CATEGORY_PERSONAL_INFORMATION, label: CATEGORY_PERSONAL_INFORMATION },
  { value: CATEGORY_DISCRIMINATION, label: CATEGORY_DISCRIMINATION },
  { value: CATEGORY_VIOLATION_OF_TERMS, label: CATEGORY_VIOLATION_OF_TERMS },
  { value: CATEGORY_COPYRIGHT, label: CATEGORY_COPYRIGHT },
  { value: CATEGORY_VIOLENCE, label: CATEGORY_VIOLENCE },
  { value: CATEGORY_CHEATING, label: CATEGORY_CHEATING },
  { value: CATEGORY_ETHICS, label: CATEGORY_ETHICS },
  { value: CATEGORY_SPAM, label: CATEGORY_SPAM },
  { value: CATEGORY_MISUSE, label: CATEGORY_MISUSE },
] as const;
