# 環境変数の一覧
# Azure AI Agent Service
AZURE_AI_FOUNDRY_PROJECT_ENDPOINT_ENV_KEY = "AZURE_AI_FOUNDRY_PROJECT_ENDPOINT"

# Azure Storage
AZURE_STORAGE_CONNECTION_STRING_ENV_KEY = "AZURE_STORAGE_CONNECTION_STRING"
AZURE_STORAGE_SRC_CONTAINER_ENV_KEY = "AZURE_STORAGE_SRC_CONTAINER"
AZURE_STORAGE_SPLIT_CONTAINER_ENV_KEY = "AZURE_STORAGE_SPLIT_CONTAINER"
AZURE_STORAGE_MARKDOWN_CONTAINER_ENV_KEY = "AZURE_STORAGE_MARKDOWN_CONTAINER"
AZURE_STORAGE_TEMPFILE_CONNECTION_STRING_ENV_KEY = (
    "AZURE_STORAGE_TEMPFILE_CONNECTION_STRING"
)
AZURE_STORAGE_TEMPFILE_CONTAINER_NAME_ENV_KEY = "AZURE_STORAGE_TEMPFILE_CONTAINER_NAME"

# Azure AI Search
AZURE_AISEARCH_ENDPOINT_ENV_KEY = "AZURE_AISEARCH_ENDPOINT"
DEFAULT_CATEGORY_ENV_KEY = "DEFAULT_CATEGORY"
SEMANTIC_SEARCH_CONFIG_ENV_KEY = "SEMANTIC_SEARCH_CONFIG"
EMBEDDING_MODEL_ENV_KEY = "EMBEDDING_MODEL"
KEYWORD_SEARCH_COUNT_ENV_KEY = "KEYWORD_SEARCH_COUNT"
SEMANTIC_SEARCH_COUNT_ENV_KEY = "SEMANTIC_SEARCH_COUNT"

# Azure OpenAI
AZURE_OPENAI_ENDPOINT_ENV_KEY = "AZURE_OPENAI_ENDPOINT"
AZURE_OPENAI_VERSION_ENV_KEY = "AZURE_OPENAI_VERSION"
AZURE_OPENAI_MODEL_NAME_ENV_KEY = "AZURE_OPENAI_MODEL_NAME"

# Scoring Profile
SCORING_PROFILE_CHUNK_ENV_KEY = "SCORING_PROFILE_CHUNK"
SCORING_PROFILE_FILEPATH_ENV_KEY = "SCORING_PROFILE_FILEPATH"
